// Types
type region = {label: string, code: string};

// export const API_KEY = 'f57d22253e934477b22a07d7cfed887d';
export const API_KEY = '80ab428a8e3e431d9db82f7876969017';
export const pageSize = 20;
export const regions: region[] = [
    {label: 'Argentina', code: 'ar'},
    {label: 'Austria', code: 'at'},
    {label: 'Australia', code: 'au'},
    {label: 'Belgium', code: 'be'},
    {label: 'Bulgaria', code: 'bg'},
    {label: 'Brasilia', code: 'br'},
    {label: 'Canada', code: 'ca'},
    {label: 'Switzerland', code: 'ch'},
    {label: 'China', code: 'cn'},
    {label: 'Colombia', code: 'co'},
    {label: 'Cuba', code: 'cu'},
    {label: 'Czech', code: 'cz'},
    {label: 'Germany', code:'de'},
    {label: 'Egypt', code: 'eg'},
    {label: 'France', code: 'fr'},
    {label: 'Great Britain', code: 'gb'},
    {label: 'Greece', code: 'gr'},
    {label: 'Hong Kong', code: 'hk'},
    {label: 'Hungary', code: 'hu'},
    {label: 'Indonesia', code: 'id'},
    {label: 'Ireland', code: 'ie'},
    {label: 'Israel', code: 'il'},
    {label: 'India', code: 'in'},
    {label: 'Italy', code: 'it'},
    {label: 'Japan', code: 'jp'},
    {label: 'South Korea', code: 'kr'},
    {label: 'Lithuania', code: 'lt'},
    {label: 'Latvia', code: 'lv'},
    {label: 'Morocco', code: 'ma'},
    {label: 'Mexico', code: 'mx'},
    {label: 'Malaysia', code: 'my'},
    {label: 'Nigeria', code: 'ng'},
    {label: 'Netherlands', code: 'nl'},
    {label: 'Norway', code: 'no'},
    {label: 'New Zealand', code: 'nz'},
    {label: 'Philippines', code: 'ph'},
    {label: 'Poland', code: 'pl'},
    {label: 'Portugal', code: 'pt'},
    {label: 'Romania', code: 'ro'},
    {label: 'Serbia', code: 'rs'},
    {label: 'Russia', code: 'ru'},
    {label: 'Saudi Arabia', code: 'sa'},
    {label: 'Sweden', code:'se'},
    {label: 'Singapore', code: 'sg'},
    {label: 'Slovenia', code: 'si'},
    {label: 'Slovakia', code: 'sk'},
    {label: 'Thailand', code: 'th'},
    {label: 'Turkey', code: 'tr'},
    {label: 'Taiwan', code: 'tw'},
    {label: 'UAE', code: 'ae'}, 
    {label: 'Ukraine', code: 'ua'},
    {label: 'USA', code:'us'},
    {label: 'Venezuela', code: 've'},
    {label: 'South Africa', code: 'za'}
];
